In [73]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Dataset 1: Student Behaviour

In [74]:
df= pd.read_csv('datasets/Student_Behaviour.csv')
df.sample(10)

,Certification Course,Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,willingness to pursue a career based on their degree,social medai & video,Travelling Time,Stress Level,Financial Status,part-time job
146,No,Male,BCA,165.0,45.0,50.0,50.0,65.0,Cinema,0 - 30 minute,Night,15000,Yes,25%,1 - 30 Minute,0 - 30 minutes,fabulous,Fabulous,Yes
172,Yes,Female,Commerce,157.0,40.0,93.0,86.0,85.0,Cinema,30 - 60 minute,Morning,15000,Yes,50%,More than 2 hour,30 - 60 minutes,Good,Bad,No
216,Yes,Female,Commerce,160.0,60.0,75.0,85.0,90.0,Cinema,2 - 3 hour,Anytime,20000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
58,Yes,Female,Commerce,152.0,60.0,93.6,85.0,93.0,Sports,1 - 2 Hour,Anytime,20000,Yes,100%,1 - 30 Minute,0 - 30 minutes,Good,good,No
49,No,Male,B.com Accounting and Finance,155.0,55.0,73.0,72.0,1.0,Reading books,1 - 2 Hour,Night,15000,Yes,75%,1 - 30 Minute,30 - 60 minutes,Good,good,No
187,Yes,Male,B.com ISM,162.0,85.0,56.0,57.0,67.0,Sports,30 - 60 minute,Night,30000,Yes,75%,30 - 60 Minute,1 - 1.30 hour,Good,good,No
5,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,0 - 30 minutes,Bad,good,No
140,Yes,Male,BCA,180.0,85.0,78.0,58.0,69.0,Sports,0 - 30 minute,Morning,12000,No,0%,1 - 30 Minute,30 - 60 minutes,Good,good,No
220,Yes,Male,Commerce,160.0,60.0,85.0,80.0,80.0,Cinema,30 - 60 minute,Anytime,20000,Yes,100%,1 - 30 Minute,30 - 60 minutes,Awful,Bad,No

In [75]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.lower() 
df.rename(columns={
    'social_medai_&_video': 'social_media_usage',
    'daily_studing_time': 'study_time',
    'college_mark': 'college_marks'
}, inplace=True)
df.sample(10)

,certification_course,gender,department,height(cm),weight(kg),10th_mark,12th_mark,college_marks,hobbies,study_time,prefer_to_study_in,salary_expectation,do_you_like_your_degree?,willingness_to_pursue_a_career_based_on_their_degree,social_media_usage,travelling_time,stress_level,financial_status,part-time_job
225,Yes,Female,Commerce,164.0,43.0,80.0,89.0,95.0,Reading books,2 - 3 hour,Morning,15000,Yes,100%,1 - 30 Minute,0 - 30 minutes,Good,good,No
179,Yes,Female,Commerce,150.0,40.0,80.0,75.0,70.0,Cinema,1 - 2 Hour,Morning,120000,Yes,50%,1 - 1.30 hour,0 - 30 minutes,Good,Bad,No
122,Yes,Male,BCA,150.0,60.0,60.0,68.1,70.0,Sports,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,30 - 60 minutes,Good,Bad,Yes
10,No,Male,BCA,99.0,50.0,75.0,70.0,60.0,Video Games,1 - 2 Hour,Morning,18000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Good,Bad,No
36,No,Female,BCA,155.0,48.0,85.0,80.0,80.0,Sports,2 - 3 hour,Anytime,15000,Yes,100%,1 - 1.30 hour,1 - 1.30 hour,Good,good,No
161,Yes,Male,Commerce,167.0,53.0,85.0,91.0,88.0,Video Games,30 - 60 minute,Morning,40000,Yes,25%,30 - 60 Minute,2 - 2.30 hour,Bad,Bad,No
48,Yes,Male,B.com Accounting and Finance,156.0,70.0,66.0,65.0,60.0,Reading books,1 - 2 Hour,Morning,20000,Yes,50%,30 - 60 Minute,30 - 60 minutes,fabulous,good,No
115,No,Male,BCA,150.0,65.0,85.0,50.0,70.0,Video Games,30 - 60 minute,Anytime,25000,Yes,75%,1.30 - 2 hour,0 - 30 minutes,Bad,Bad,No
167,Yes,Male,Commerce,170.0,90.0,75.0,75.0,80.0,Sports,30 - 60 minute,Anytime,40000,Yes,75%,1 - 1.30 hour,1.30 - 2 hour,Good,good,No
230,Yes,Male,B.com ISM,170.0,76.0,72.0,67.0,65.0,Video Games,30 - 60 minute,Morning,7000,Yes,50%,More than 2 hour,30 - 60 minutes,Bad,Bad,No

In [76]:
df.isnull().sum()

certification_course                                    0
gender                                                  0
department                                              0
height(cm)                                              0
weight(kg)                                              0
10th_mark                                               0
12th_mark                                               0
college_marks                                           0
hobbies                                                 0
study_time                                              0
prefer_to_study_in                                      0
salary_expectation                                      0
do_you_like_your_degree?                                0
willingness_to_pursue_a_career_based_on_their_degree    0
social_media_usage                                      0
travelling_time                                         0
stress_level                                            0
financial_status                                        0
part-time_job                                           0
dtype: int64

In [77]:
binary_cols=[
    'certification_course',
    'do_you_like_your_degree?',
    'part-time_job'
]
for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

In [78]:
df['financial_status'].unique()

array(['Bad', 'good', 'Awful', 'Fabulous'], dtype=object)

In [79]:
df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})
df['financial_status'] = df['financial_status'].map({
    'Fabulous':2,
    'good':4,
    'Bad':7,
    'Awful':9
})

In [80]:
df['study_time'].unique()

array(['0 - 30 minute', '30 - 60 minute', '1 - 2 Hour', '2 - 3 hour',
       '3 - 4 hour', 'More Than 4 hour'], dtype=object)

In [81]:
df['study_time']=df['study_time'].map({
    '0 - 30 minute':0.25,
    '30 - 60 minute':0.75,
    '1 - 2 Hour':1.5,
    '2 - 3 hour':2.5,
    '3 - 4 hour':3.5,
    'More Than 4 hour':5
})

In [82]:
df['stress_level'].unique()

array(['Bad', 'Awful', 'Good', 'fabulous'], dtype=object)

In [83]:
df['stress_level']=df['stress_level'].map({
    'fabulous':2,
    'Good':4,
    'Bad':7,
    'Awful':9
})

In [84]:
df['social_media_usage'].unique()

array(['1.30 - 2 hour', '1 - 1.30 hour', 'More than 2 hour',
       '30 - 60 Minute', '1 - 30 Minute', '0 Minute'], dtype=object)

In [85]:
df['social_media_usage'] = df['social_media_usage'].map({
    '1.30 - 2 hour': 1.75,
    '1 - 1.30 hour': 1.25,
    'More than 2 hour': 3,
    '30 - 60 Minute': 0.75,
    '1 - 30 Minute': 0.5,
    '0 Minute': 0
})

In [86]:
df['travelling_time'].unique()

array(['30 - 60 minutes', '0 - 30 minutes', '1 - 1.30 hour',
       '2 - 2.30 hour', '1.30 - 2 hour', 'more than 3 hour',
       '2.30 - 3 hour'], dtype=object)

In [87]:
df['travelling_time'] = df['travelling_time'].str.lower().map({
    '30 - 60 minutes': 0.45,
    '0 - 30 minutes': 0.15,
    '1 - 1.30 hour': 1.15,
    '2 - 2.30 hour':2.15,
    '1.30 - 2 hour':1.45,
    '2.30 - 3 hour':2.5,
    'more than 3 hour': 3.5
})

In [88]:
df['willingness_to_pursue_a_career_based_on_their_degree'].unique()

array(['50%', '75%', '25%', '100%', '0%'], dtype=object)

In [89]:
df['career_alignment'] = df['willingness_to_pursue_a_career_based_on_their_degree'].str.replace('%', '').astype(int)
df['career_alignment'] = df['career_alignment'] / 100

In [90]:
df.drop([
    'height(cm)',
    'weight(kg)',
    'hobbies',
    'salary_expectation',
    'prefer_to_study_in',
    'department',
    'willingness_to_pursue_a_career_based_on_their_degree'
], axis=1, inplace=True)

In [91]:
# New column: Academic pressure
df['academic_pressure'] = (
    df['study_time'] * (100 - df['college_marks'])
)

# New column: Lifestyle stress
df['lifestyle_stress'] = (
    df['social_media_usage'] + df['travelling_time']
)

In [92]:
df.drop([
    '10th_mark',
    '12th_mark',
    'certification_course'
], axis=1, inplace=True)

In [93]:
df.sample(10)

,gender,college_marks,study_time,do_you_like_your_degree?,social_media_usage,travelling_time,stress_level,financial_status,part-time_job,career_alignment,academic_pressure,lifestyle_stress
156,0,80.0,0.75,1,1.25,2.15,4,4,0,0.75,15.00,3.40
164,0,80.0,0.75,1,0.75,3.50,4,7,0,1.00,15.00,4.25
120,1,80.0,2.50,1,0.75,0.15,4,4,1,0.75,50.00,0.90
158,0,35.0,3.50,1,3.00,1.15,4,7,0,0.75,227.50,4.15
10,0,60.0,1.50,1,1.25,0.15,4,7,0,0.75,60.00,1.40
183,0,2.0,0.25,1,3.00,1.15,4,4,0,1.00,24.50,4.15
189,0,70.0,1.50,1,0.50,0.15,4,9,0,0.50,45.00,0.65
119,0,75.0,0.25,1,3.00,0.15,7,4,0,0.75,6.25,3.15
232,1,70.0,0.75,1,0.75,2.50,7,4,0,0.50,22.50,3.25
53,1,85.0,1.50,1,1.75,3.50,4,7,0,1.00,22.50,5.25

# Dataset 2: Stress Factors

In [94]:
df1=pd.read_csv('datasets/Stress_Factor.csv')
df1.sample(10)

,Kindly Rate your Sleep Quality 😴,How many times a week do you suffer headaches 🤕?,How would you rate you academic performance 👩‍🎓?,how would you rate your study load?,How many times a week you practice extracurricular activities 🎾?,How would you rate your stress levels?
494,4,2,4,3,5,3
166,4,3,3,4,2,2
202,3,2,3,5,4,3
292,2,1,2,4,3,3
518,3,4,3,5,2,5
259,1,1,5,1,5,1
221,4,1,4,4,1,1
411,3,2,4,2,3,1
203,3,2,4,2,3,1
388,2,3,4,2,5,3

In [95]:
df1.isnull().sum()

Kindly Rate your Sleep Quality 😴                                    0
How many times a week do you suffer headaches 🤕?                    0
How would you rate you academic performance 👩‍🎓?                    0
how would you rate your study load?                                 0
How many times a week you practice extracurricular activities 🎾?    0
How would you rate your stress levels?                              0
dtype: int64

In [96]:
df.columns = df.columns.str.strip().str.lower()

In [97]:
df1.rename(columns={
    'Kindly Rate your Sleep Quality 😴': 'sleep_quality',
    'How many times a week do you suffer headaches 🤕?': 'headache_freq',
    'How would you rate you academic performance 👩‍🎓?': 'academic_performance',
    'how would you rate your study load?': 'study_load',
    'How many times a week you practice extracurricular activities 🎾?': 'extracurricular_freq',
    'How would you rate your stress levels?': 'stress_level'
}, inplace=True)
df1.sample(10)

,sleep_quality,headache_freq,academic_performance,study_load,extracurricular_freq,stress_level
290,1,2,3,3,1,4
55,3,2,4,5,4,5
293,4,2,3,3,1,4
178,3,5,3,2,3,5
435,2,3,3,2,3,4
399,4,4,2,3,1,3
173,3,5,2,1,1,1
100,2,4,3,2,1,2
447,5,2,3,2,3,4
251,2,1,4,4,1,3

In [98]:
df1['sleep_quality'].unique()

array([3, 4, 2, 1, 5])

In [99]:
scaler = MinMaxScaler()
cols = [
    'sleep_quality',
    'headache_freq',
    'academic_performance',
    'study_load',
    'extracurricular_freq',
    'stress_level'
]

df1[cols] = scaler.fit_transform(df1[cols])

In [100]:
df1.sample(10)

,sleep_quality,headache_freq,academic_performance,study_load,extracurricular_freq,stress_level
474,1.00,0.25,0.75,0.75,0.75,0.25
190,0.25,0.50,0.50,0.25,1.00,0.25
33,0.25,0.50,0.75,0.00,0.25,0.25
104,0.50,0.00,0.50,0.75,0.25,0.50
220,0.25,0.50,0.50,0.75,0.75,0.50
133,0.50,0.75,0.25,0.00,0.50,0.00
231,0.50,0.00,0.75,0.75,0.25,0.50
195,0.50,0.25,0.50,0.00,0.00,1.00
421,0.50,0.00,0.50,0.25,0.00,0.00
23,0.50,0.00,0.75,0.75,0.25,0.50

In [101]:
df1['mental_strain'] = (df1['stress_level'] + df1['study_load'] + df1['headache_freq'])
df1['recovery_score']=df1['sleep_quality']+df1['extracurricular_freq']
df1['performance_pressure']=(df1['study_load']*(1-df1['academic_performance']))

In [104]:
df1['burnout_score'] = (0.4 * df1['mental_strain'] +0.3 * (1 - df1['recovery_score']) +0.3 * df1['performance_pressure'])
df1['burnout_level'] = pd.qcut(
    df1['burnout_score'],
    q=3,
    labels=['Low', 'Medium', 'High']
)

# Dataset 3: Student Mental Health